src/app.py
from flask import Flask, render_template, redirect

from src.common.database import Database
from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint

app = Flask(__name__)
app.config.from_object("src.config")
app.secret_key = "123"


# Initialize the database
@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.jinja2')


app.register_blueprint(user_blueprint, url_prefix="/users")
# Register the blue print with the prefix 'users'
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

src/models/alerts/views.py
from flask import Blueprint

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/')
def index():
    return "This is the alert index"


@alert_blueprint.route('/new', methods=['POST'])
def create_alert():
    pass


@alert_blueprint.route('/deactivate/<string:alert_id>')
def deactivate_alert(alert_id):
    pass


# Check existing alert
@alert_blueprint.route('/alert/<string:alert_id>')
def get_alert_page(alert_id):
    pass

src/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

# remove load_an_item
@item_blueprint.route('/load')
def load_an_item():
    """

    :return:
    """
    pass

src/models/stores/views.py
from flask import Blueprint

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/store/<string:name>')
def store_page():
    pass

@store_blueprint.route('/')
def index():
    return "This is the store index"

src/models/users/views.py
# About the blueprint

from flask import Blueprint, request, session, url_for, render_template
from werkzeug.utils import redirect

from src.models.users.user import User
from src.models.users.errors import UserErrors
# from src.models.users.errors import IncorrectPasswordError

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['POST', 'GET'])
def login_user():
    # 两种不同的 methods 对应不同的动作
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']  # Hashed pw from user input form

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors as e:
            return e.message

    return render_template("users/login.jinja2")


@user_blueprint.route('/register', methods=['GET','POST'])
def register_user():
    # If a user does not exist, register it and then log it in
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']  # Hashed pw from user input form

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors as e:
            return e.message

    return render_template('users/register.jinja2')


@user_blueprint.route('/alerts')
def user_alerts():
    """
    find user from the browser session, and find all the alerts with user's email
    :return: render_template; for the `alerts=alerts` parameter, the former one is render_template()'s para,
        the latter one is the alerts get from user
    """
    user = User.find_user_by_email(session['email'])
    alerts = user.get_alert()
    return render_template("users/alerts.jinja2", alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))  # return the page back to Home; `'home'` is the home() function in app.py


# Check all the alerts for specific user
@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends base.jinja2 %}
{% block content %}
    <div class="page-header">
        <h1>Alerts</h1>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/alerts/new_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing service</title>

    {%include 'html_dependencies.jinja2' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Pricing</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('stores.index')}}">Stores</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('alerts.index')}}">Alerts</a>
            </li>
        </ul>

        {% if session["email"] %}
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('users.user_alerts')}}"><i class="fas fa-bell"></i> Your Alerts</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('users.logout_user')}}"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                </li>
            </ul>

        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('users.register_user')}}"><i class="fas fa-user-plus"></i> Register</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('users.login_user')}}"><i class="fas fa-sign-in-alt"></i> Log In</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>


{% block content%} {% endblock %}


</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Price tracking service</h1>
        <p class="lead">To use this service, register as a user and prepare an item link for tracking.</p>
        <p>Click register to join.</p>
        <hr class="my-4">
        <button type="button" class="btn btn-outline-dark" href="{{ url_for('users.register_user')}}">Register</button>
    </div>
</div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>

src/templates/stores/create_store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/stores/edit_store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/stores/store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/stores/store_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div>
            <h1>Alerts <small>Showing existing alerts</small></h1>
        </div>
    </div>

    <div class="list-group">
        {% for alert in alerts %}
            <a href="#" class="list-group-item">
                <h4 class="list-group-item-header">Alert for {{ alert.item.name }}</h4>
                <p class="list-group-item-text">Latest price: {{ alert.item.price }}<br/>
                Last checked time: {{ alert.last_checked.strftime("%d-%m-%y") }}</p>
            </a>
        {% endfor %}
    </div>


{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="form">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email"
                       aria-describedby="emailHelpBlock">
                <span id="emailHelpBlock" class="help-block">Be sure to enter a valid e-mail, as that's where we'll send alerts.</span>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Log In</button>
        </form>
    </div>

{% endblock %}

src/templates/users/register.jinja2
{% extend "base.jinja2" %}
{% block content %}
    <form>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>
    </form>

{% endblock %}